server:
  port: 9005
spring:
  main:
    allow-bean-definition-overriding: true #允许多个Feign接口都指向一个服务
  application:
    name: search
  elasticsearch:
    rest:
      uris: 192.168.232.128:9200  #此处配置elasticsearch的访问地址
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
#超时配置
ribbon:
  ReadTimeout: 300000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
logging:
  level:
    com:
      offcn: debug


