server:
  port: 9006
spring:
  application:
    name: sms
  rabbitmq:
    host: 192.168.232.128
    port: 5672
    username: guest
    password: guest
sms:
  appcode: caa262e7e256434ba3426071400f89b4  #使用自己的AppCode
  tpl_id: TP1711063    # 默认模板