server:
  port: 9009
spring:
  application:
    name: pay
  #MQ地址
  rabbitmq:
    host: 192.168.232.128
    port: 5672
    username: guest
    password: guest
  main:
    allow-bean-definition-overriding: true
#  redis:
#    host: 192.168.188.128
#    port: 6379
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
#hystrix 配置
hystrix:
  command:
    default:
      execution:
        timeout:
          #如果enabled设置为false，则请求超时交给ribbon控制
          enabled: true
        isolation:
          strategy: SEMAPHORE

#微信支付信息配置
weixin:
  appid: wx8397f8696b538317 #应用id
  partner: 1473426802       #商户id
  partnerkey: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb #秘钥
  #http://huangfei.vaiwan.com外网域名，内网穿透生成
  notifyurl: http://huangfei.vaiwan.com/weixin/pay/notify/url  #支付回调地址

##配置消息队列名称
#mq:
#  queue: order.payMessage.queue
